/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package schoolmanagementsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.jOptionPane;
import javax.swing.table.DefaultTableModel;
import schoolmanagementsystem.Database.Homework;
import schoolmanagementsystem.Database.Notice;
import schoolmanagementsystem.Database.StudentDatabase;

/**
 *
 * @author Administrator
 */

public class StudentProfile extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    StudentDatabase stdb;
    List<Homework> homeworkList;
    int totalHomeworks=0;
    int toggleHomework=0;
    public String id;
    
    //Constructor
    public StudentProfile() {
        this.setUndecorated(true);
        initComponents();
        hideSideMenu();
    }
    //Constructor (Polymorphism - Method Overloading)
    public StudentProfile(String id) {
        this.setUndecorated(true);
        initComponents();
        this.id=id;
        stdb=new StudentDatabase(this.id);
        showNoticeBoard();
        getHomeworks();
        hideSideMenu();
        profileShow();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TopBar = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        sideMenu = new javax.swing.JPanel();
        home_btn = new javax.swing.JPanel();
        ind_0 = new javax.swing.JPanel();
        Home1 = new javax.swing.JLabel();
        homework_btn = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        Homework = new javax.swing.JLabel();
        result_btn = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        ResultLebel = new javax.swing.JLabel();
        attendance_btn = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        AttendenceLebel = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        notices_btn = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        noticeLebel = new javax.swing.JLabel();
        sideMenuHide = new javax.swing.JLabel();
        messege_btn = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        messegeLebel = new javax.swing.JLabel();
        LeftCeditPanel = new javax.swing.JPanel();
        MenuText = new javax.swing.JLabel();
        SideMenuShow = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        NameFDB = new javax.swing.JLabel();
        SectionText = new javax.swing.JLabel();
        Section = new javax.swing.JLabel();
        NameText2 = new javax.swing.JLabel();
        IDTest1 = new javax.swing.JLabel();
        IDFDB = new javax.swing.JLabel();
        ClassText = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        Edit = new javax.swing.JLabel();
        HomeworkPanel = new javax.swing.JPanel();
        HomeworkPanel1 = new javax.swing.JPanel();
        dueDateLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        homeworkLabel = new javax.swing.JLabel();
        totalMarksLabel = new javax.swing.JLabel();
        postDateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        previousHomeworkButton = new javax.swing.JButton();
        nextHomeworkButton = new javax.swing.JButton();
        AttendencePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        noticePanel = new javax.swing.JPanel();
        HomeworkPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        myNoticePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noticeBoardTable = new javax.swing.JTable();
        resultPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        MessegePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBar.setBackground(new java.awt.Color(19, 10, 52));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystem/image/close.png"))); // NOI18N
        close_btn.setBorder(null);
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLayout.createSequentialGroup()
                .addGap(0, 540, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 570, 30));

        sideMenu.setBackground(new java.awt.Color(19, 10, 52));

        home_btn.setBackground(new java.awt.Color(65, 59, 94));
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });

        ind_0.setBackground(new java.awt.Color(255, 255, 255));
        ind_0.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_0Layout = new javax.swing.GroupLayout(ind_0);
        ind_0.setLayout(ind_0Layout);
        ind_0Layout.setHorizontalGroup(
            ind_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_0Layout.setVerticalGroup(
            ind_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        Home1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Home1.setForeground(new java.awt.Color(255, 255, 255));
        Home1.setText("Home");

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_btnLayout.createSequentialGroup()
                .addComponent(ind_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                    .addContainerGap(58, Short.MAX_VALUE)
                    .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_0, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
            .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(home_btnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Home1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        homework_btn.setBackground(new java.awt.Color(19, 10, 52));
        homework_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homework_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homework_btnMousePressed(evt);
            }
        });

        ind_1.setBackground(new java.awt.Color(255, 255, 255));
        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Homework.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Homework.setForeground(new java.awt.Color(255, 255, 255));
        Homework.setText("Homework");

        javax.swing.GroupLayout homework_btnLayout = new javax.swing.GroupLayout(homework_btn);
        homework_btn.setLayout(homework_btnLayout);
        homework_btnLayout.setHorizontalGroup(
            homework_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homework_btnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Homework)
                .addGap(0, 81, Short.MAX_VALUE))
        );
        homework_btnLayout.setVerticalGroup(
            homework_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(Homework, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        result_btn.setBackground(new java.awt.Color(19, 10, 52));
        result_btn.setForeground(new java.awt.Color(255, 255, 255));
        result_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                result_btnMousePressed(evt);
            }
        });

        ind_2.setBackground(new java.awt.Color(255, 255, 255));
        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ResultLebel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ResultLebel.setForeground(new java.awt.Color(255, 255, 255));
        ResultLebel.setText("Result");

        javax.swing.GroupLayout result_btnLayout = new javax.swing.GroupLayout(result_btn);
        result_btn.setLayout(result_btnLayout);
        result_btnLayout.setHorizontalGroup(
            result_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_btnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ResultLebel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        result_btnLayout.setVerticalGroup(
            result_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addComponent(ResultLebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        attendance_btn.setBackground(new java.awt.Color(19, 10, 52));
        attendance_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendance_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendance_btnMousePressed(evt);
            }
        });

        ind_4.setBackground(new java.awt.Color(255, 255, 255));
        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        AttendenceLebel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AttendenceLebel.setForeground(new java.awt.Color(255, 255, 255));
        AttendenceLebel.setText("Attendance");
        AttendenceLebel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttendenceLebelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout attendance_btnLayout = new javax.swing.GroupLayout(attendance_btn);
        attendance_btn.setLayout(attendance_btnLayout);
        attendance_btnLayout.setHorizontalGroup(
            attendance_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendance_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(AttendenceLebel)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        attendance_btnLayout.setVerticalGroup(
            attendance_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AttendenceLebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(ind_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logOut.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("LogOut");
        logOut.setBorder(null);
        logOut.setBorderPainted(false);
        logOut.setContentAreaFilled(false);
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        notices_btn.setBackground(new java.awt.Color(19, 10, 52));
        notices_btn.setForeground(new java.awt.Color(255, 255, 255));
        notices_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notices_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notices_btnMousePressed(evt);
            }
        });

        ind_3.setBackground(new java.awt.Color(255, 255, 255));
        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        noticeLebel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        noticeLebel.setForeground(new java.awt.Color(255, 255, 255));
        noticeLebel.setText("Notices");

        javax.swing.GroupLayout notices_btnLayout = new javax.swing.GroupLayout(notices_btn);
        notices_btn.setLayout(notices_btnLayout);
        notices_btnLayout.setHorizontalGroup(
            notices_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notices_btnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(noticeLebel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        notices_btnLayout.setVerticalGroup(
            notices_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(noticeLebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu.jpg"))); // NOI18N
        sideMenuHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideMenuHideMouseClicked(evt);
            }
        });

        messege_btn.setBackground(new java.awt.Color(19, 10, 52));
        messege_btn.setForeground(new java.awt.Color(255, 255, 255));
        messege_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messege_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                messege_btnMousePressed(evt);
            }
        });

        ind_5.setBackground(new java.awt.Color(255, 255, 255));
        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        messegeLebel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        messegeLebel.setForeground(new java.awt.Color(255, 255, 255));
        messegeLebel.setText("Messege");

        javax.swing.GroupLayout messege_btnLayout = new javax.swing.GroupLayout(messege_btn);
        messege_btn.setLayout(messege_btnLayout);
        messege_btnLayout.setHorizontalGroup(
            messege_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messege_btnLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(messegeLebel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        messege_btnLayout.setVerticalGroup(
            messege_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(messegeLebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendance_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notices_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homework_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOut)
                .addGap(25, 25, 25))
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addComponent(sideMenuHide)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(result_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(messege_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addComponent(sideMenuHide)
                .addGap(40, 40, 40)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homework_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attendance_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notices_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(result_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messege_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1.add(sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 690));

        LeftCeditPanel.setBackground(new java.awt.Color(65, 59, 94));

        MenuText.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        MenuText.setForeground(new java.awt.Color(255, 255, 255));
        MenuText.setText("Menu");

        SideMenuShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu.jpg"))); // NOI18N
        SideMenuShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SideMenuShowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LeftCeditPanelLayout = new javax.swing.GroupLayout(LeftCeditPanel);
        LeftCeditPanel.setLayout(LeftCeditPanelLayout);
        LeftCeditPanelLayout.setHorizontalGroup(
            LeftCeditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
            .addGroup(LeftCeditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftCeditPanelLayout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(MenuText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
            .addGroup(LeftCeditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LeftCeditPanelLayout.createSequentialGroup()
                    .addComponent(SideMenuShow)
                    .addGap(0, 207, Short.MAX_VALUE)))
        );
        LeftCeditPanelLayout.setVerticalGroup(
            LeftCeditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(LeftCeditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftCeditPanelLayout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(MenuText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(644, Short.MAX_VALUE)))
            .addGroup(LeftCeditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftCeditPanelLayout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addComponent(SideMenuShow)
                    .addContainerGap(647, Short.MAX_VALUE)))
        );

        jPanel1.add(LeftCeditPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 247, 720));

        HomePanel.setBackground(new java.awt.Color(65, 59, 94));

        NameFDB.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        NameFDB.setForeground(new java.awt.Color(51, 255, 255));
        NameFDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameFDB.setText("Name Show");

        SectionText.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        SectionText.setForeground(new java.awt.Color(255, 255, 255));
        SectionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SectionText.setText("Section:");

        Section.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Section.setForeground(new java.awt.Color(153, 255, 255));
        Section.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Section.setText("Section show");

        NameText2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        NameText2.setForeground(new java.awt.Color(255, 255, 255));
        NameText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameText2.setText("Name:");

        IDTest1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        IDTest1.setForeground(new java.awt.Color(255, 255, 255));
        IDTest1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDTest1.setText("ID:");

        IDFDB.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        IDFDB.setForeground(new java.awt.Color(153, 255, 255));
        IDFDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDFDB.setText("ID show");

        ClassText.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ClassText.setForeground(new java.awt.Color(255, 255, 255));
        ClassText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassText.setText("Class:");

        Class.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Class.setForeground(new java.awt.Color(153, 255, 255));
        Class.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Class.setText("Class show");

        Edit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("Edit");
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(NameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(IDTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(IDFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClassText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SectionText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(559, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(95, 95, 95)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ClassText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SectionText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        jTabbedPane1.addTab("home", HomePanel);

        HomeworkPanel1.setBackground(new java.awt.Color(65, 59, 94));

        dueDateLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        dueDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dueDateLabel.setText("Due Date :");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HomeWork");

        subjectLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        subjectLabel.setForeground(new java.awt.Color(255, 255, 255));
        subjectLabel.setText("Subject : Math");

        homeworkLabel.setBackground(new java.awt.Color(0, 0, 0));
        homeworkLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeworkLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeworkLabel.setText("Homework");

        totalMarksLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        totalMarksLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMarksLabel.setText("Total Marks : 10");

        postDateLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        postDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        postDateLabel.setText("Post Date : ");

        jPanel2.setBackground(new java.awt.Color(65, 59, 94));
        jPanel2.setMinimumSize(new java.awt.Dimension(231, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previousHomeworkButton.setBackground(new java.awt.Color(102, 102, 255));
        previousHomeworkButton.setFont(new java.awt.Font("Century Schoolbook", 1, 48)); // NOI18N
        previousHomeworkButton.setForeground(new java.awt.Color(255, 255, 255));
        previousHomeworkButton.setText("<");
        previousHomeworkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousHomeworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousHomeworkButtonActionPerformed(evt);
            }
        });
        jPanel2.add(previousHomeworkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 66, 39));

        nextHomeworkButton.setBackground(new java.awt.Color(102, 102, 255));
        nextHomeworkButton.setFont(new java.awt.Font("Century Schoolbook", 1, 48)); // NOI18N
        nextHomeworkButton.setForeground(new java.awt.Color(255, 255, 255));
        nextHomeworkButton.setText(">");
        nextHomeworkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextHomeworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextHomeworkButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nextHomeworkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 66, 39));

        javax.swing.GroupLayout HomeworkPanel1Layout = new javax.swing.GroupLayout(HomeworkPanel1);
        HomeworkPanel1.setLayout(HomeworkPanel1Layout);
        HomeworkPanel1Layout.setHorizontalGroup(
            HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                .addGroup(HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeworkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                                .addGroup(HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                                        .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(totalMarksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(postDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        HomeworkPanel1Layout.setVerticalGroup(
            HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(postDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMarksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(homeworkLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeworkPanelLayout = new javax.swing.GroupLayout(HomeworkPanel);
        HomeworkPanel.setLayout(HomeworkPanelLayout);
        HomeworkPanelLayout.setHorizontalGroup(
            HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1047, Short.MAX_VALUE)
            .addGroup(HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeworkPanelLayout.createSequentialGroup()
                    .addComponent(HomeworkPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        HomeworkPanelLayout.setVerticalGroup(
            HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeworkPanelLayout.createSequentialGroup()
                    .addComponent(HomeworkPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("homework", HomeworkPanel);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("Attendance");

        javax.swing.GroupLayout AttendencePanelLayout = new javax.swing.GroupLayout(AttendencePanel);
        AttendencePanel.setLayout(AttendencePanelLayout);
        AttendencePanelLayout.setHorizontalGroup(
            AttendencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendencePanelLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel10)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        AttendencePanelLayout.setVerticalGroup(
            AttendencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendencePanelLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(386, 386, 386))
        );

        jTabbedPane1.addTab("attendence", AttendencePanel);

        HomeworkPanel2.setBackground(new java.awt.Color(65, 59, 94));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Notice");

        noticeBoardTable.setAutoCreateRowSorter(true);
        noticeBoardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Teacher Name", "Subject", "Notice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        noticeBoardTable.setRowHeight(30);
        jScrollPane1.setViewportView(noticeBoardTable);
        if (noticeBoardTable.getColumnModel().getColumnCount() > 0) {
            noticeBoardTable.getColumnModel().getColumn(0).setMinWidth(100);
            noticeBoardTable.getColumnModel().getColumn(0).setMaxWidth(100);
            noticeBoardTable.getColumnModel().getColumn(1).setMinWidth(100);
            noticeBoardTable.getColumnModel().getColumn(1).setMaxWidth(100);
            noticeBoardTable.getColumnModel().getColumn(2).setMinWidth(150);
            noticeBoardTable.getColumnModel().getColumn(2).setMaxWidth(250);
            noticeBoardTable.getColumnModel().getColumn(3).setMinWidth(100);
            noticeBoardTable.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        javax.swing.GroupLayout myNoticePanelLayout = new javax.swing.GroupLayout(myNoticePanel);
        myNoticePanel.setLayout(myNoticePanelLayout);
        myNoticePanelLayout.setHorizontalGroup(
            myNoticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myNoticePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        myNoticePanelLayout.setVerticalGroup(
            myNoticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myNoticePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout HomeworkPanel2Layout = new javax.swing.GroupLayout(HomeworkPanel2);
        HomeworkPanel2.setLayout(HomeworkPanel2Layout);
        HomeworkPanel2Layout.setHorizontalGroup(
            HomeworkPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(808, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeworkPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myNoticePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeworkPanel2Layout.setVerticalGroup(
            HomeworkPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myNoticePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout noticePanelLayout = new javax.swing.GroupLayout(noticePanel);
        noticePanel.setLayout(noticePanelLayout);
        noticePanelLayout.setHorizontalGroup(
            noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noticePanelLayout.createSequentialGroup()
                .addComponent(HomeworkPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        noticePanelLayout.setVerticalGroup(
            noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noticePanelLayout.createSequentialGroup()
                .addComponent(HomeworkPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("notice", noticePanel);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("Result");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel12)
                .addContainerGap(675, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(368, 368, 368))
        );

        jTabbedPane1.addTab("result", resultPanel);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setText("Messege");

        javax.swing.GroupLayout MessegePanelLayout = new javax.swing.GroupLayout(MessegePanel);
        MessegePanel.setLayout(MessegePanelLayout);
        MessegePanelLayout.setHorizontalGroup(
            MessegePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessegePanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel13)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        MessegePanelLayout.setVerticalGroup(
            MessegePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessegePanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(368, 368, 368))
        );

        jTabbedPane1.addTab("Messege", MessegePanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //......................Start Custom Functions...................//
    public void getHomeworks(){
        homeworkList=stdb.getHomework();
        totalHomeworks=homeworkList.size();
        showHomework();
    }
    public void showHomework(){
        if(totalHomeworks>=1){
            nextHomeworkButton.setVisible(true);
            subjectLabel.setText("Subject : "+homeworkList.get(0).getSubject());
            totalMarksLabel.setText("Total Marks : "+homeworkList.get(0).getTotalMarks());
            postDateLabel.setText("Post Date : "+homeworkList.get(0).getPostDate());
            dueDateLabel.setText("Due Date : "+homeworkList.get(0).getDueDateString());
            homeworkLabel.setText("<html>"+homeworkList.get(0).getHomeworkText()+"</html>");
        }else{
            nextHomeworkButton.setVisible(false);
            previousHomeworkButton.setVisible(false);
            subjectLabel.setText("");
            totalMarksLabel.setText("");
            postDateLabel.setText("");
            dueDateLabel.setText("");
            homeworkLabel.setText("Hey, You have no homework to do. Enjoy your free time. Thank you.");
            
        }
    }
    public void nextHomework(){
        toggleHomework++;
        toggleHomework%=totalHomeworks;
        if(toggleHomework==0){
            previousHomeworkButton.setVisible(false);
            showHomework();
        }
        else if(totalHomeworks>=1&&toggleHomework<totalHomeworks){
            previousHomeworkButton.setVisible(true);
            subjectLabel.setText("Subject : "+homeworkList.get(toggleHomework).getSubject());
            totalMarksLabel.setText("Total Marks : "+homeworkList.get(toggleHomework).getTotalMarks());
            postDateLabel.setText("Post Date : "+homeworkList.get(toggleHomework).getPostDate());
            dueDateLabel.setText("Due Date : "+homeworkList.get(toggleHomework).getDueDateString());
            homeworkLabel.setText("<html>"+homeworkList.get(toggleHomework).getHomeworkText()+"</html>");
        }
    }
    public void previousHomework(){
        toggleHomework--;
        if(toggleHomework<0){
            toggleHomework=0;
            previousHomeworkButton.setVisible(false);
            showHomework();
        }
        else if(toggleHomework==0){
            previousHomeworkButton.setVisible(false);
            showHomework();
        }
        else if(totalHomeworks>=1&&toggleHomework>=0){
            subjectLabel.setText("Subject : "+homeworkList.get(toggleHomework).getSubject());
            totalMarksLabel.setText("Total Marks : "+homeworkList.get(toggleHomework).getTotalMarks());
            postDateLabel.setText("Post Date : "+homeworkList.get(toggleHomework).getPostDate());
            dueDateLabel.setText("Due Date : "+homeworkList.get(toggleHomework).getDueDateString());
            homeworkLabel.setText("<html>"+homeworkList.get(toggleHomework).getHomeworkText()+"</html>");
        }
    }
    
    
    public void showNoticeBoard(){
        
        DefaultTableModel dtm = (DefaultTableModel) noticeBoardTable.getModel();
        
        List<Notice> list=stdb.getNotice();
        Object[] row=new Object[5];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getDateString();
            row[1]=list.get(i).getTimeString();
            row[2]=list.get(i).getTeacherName();
            row[3]=list.get(i).getSubject();
            row[4]=list.get(i).getNotice();
            dtm.addRow(row);
        }
    }
    
    int x =242;
    public void hideSideMenu(){
        if(x==242)
        {
            sideMenu.setSize(242,720);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i = 242;i>=0;i=i-11){
                            Thread.sleep(1);
                            sideMenu.setSize(i,720);
                        }
                    }catch(Exception e){
                        jOptionPane.showMessegeDialog(null,e);
                    }
                }
            };th.start();
            x=0;
        }
    }
    
    public void profileShow(){
        
        String student_id =this.id;
        
        String StudentName = stdb.getStudentName();
        NameFDB.setText(StudentName);
        IDFDB.setText(student_id);
        Section.setText(stdb.getSection());
        Class.setText(stdb.getStudentClass());
        
    }
    
//......................End Custom Functions...................//
    
    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed
        
        jTabbedPane1.setSelectedIndex(0);
        setColor(home_btn);
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        resetColor(messege_btn);
        
        ind_0.setOpaque(true);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
    }//GEN-LAST:event_home_btnMousePressed

    private void homework_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homework_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        setColor(homework_btn);
        resetColor(home_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        resetColor(messege_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(true);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
    }//GEN-LAST:event_homework_btnMousePressed

    private void result_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_result_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        setColor(result_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(homework_btn);
        resetColor(home_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        resetColor(messege_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(true);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
        
    }//GEN-LAST:event_result_btnMousePressed

    private void notices_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notices_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        setColor(notices_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(home_btn);
        resetColor(attendance_btn);
        resetColor(messege_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(true);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
        
        
    }//GEN-LAST:event_notices_btnMousePressed

    private void attendance_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendance_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        setColor(attendance_btn);
        resetColor(home_btn);
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(messege_btn);
        
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(true);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
        
        
    }//GEN-LAST:event_attendance_btnMousePressed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        stdb.logout();
        logInPage LP= new logInPage();
        LP.setVisible(true);
        LP.setResizable(false);
        dispose();
    }//GEN-LAST:event_logOutActionPerformed
    
    private void sideMenuHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuHideMouseClicked
        if(x==242)
        {
            sideMenu.setSize(242,720);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i = 242;i>=0;i--){
                            Thread.sleep(1);
                            sideMenu.setSize(i,720);
                        }
                    }catch(Exception e){
                        jOptionPane.showMessegeDialog(null,e);
                    }
                }
            };th.start();
            x=0;
        }
    }//GEN-LAST:event_sideMenuHideMouseClicked

    private void SideMenuShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideMenuShowMouseClicked
        if(x == 0)
        {
            sideMenu.show();
            jTabbedPane1.show();
            //jTabbedPane2.show();
            sideMenu.setSize(242,720);//[418, 720]
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            sideMenu.setSize(i,720);
                        }
                    }catch(Exception e){
                        jOptionPane.showMessegeDialog(null,e);
                    }
                }
            };th.start();
            x=242;
        }
    }//GEN-LAST:event_SideMenuShowMouseClicked

    private void AttendenceLebelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendenceLebelMouseClicked
        jTabbedPane1.setSelectedIndex(2);
        setColor(attendance_btn);
        resetColor(home_btn);
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(messege_btn);
        
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(true);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
    }//GEN-LAST:event_AttendenceLebelMouseClicked

    private void messege_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messege_btnMousePressed
        jTabbedPane1.setSelectedIndex(5);
        setColor(messege_btn);
        resetColor(home_btn);
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(true);
    }//GEN-LAST:event_messege_btnMousePressed

    private void previousHomeworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousHomeworkButtonActionPerformed
        previousHomework();
    }//GEN-LAST:event_previousHomeworkButtonActionPerformed

    private void nextHomeworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextHomeworkButtonActionPerformed
        nextHomework();
    }//GEN-LAST:event_nextHomeworkButtonActionPerformed

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        UpdateAccountStudent updateAccountStudent = new UpdateAccountStudent(this.id);
        updateAccountStudent.setVisible(true);

        updateAccountStudent.setResizable(false);

        updateAccountStudent.setDefaultCloseOperation(updateAccountStudent.DO_NOTHING_ON_CLOSE);

        //popUp pU = new popUp();
        dispose();
    }//GEN-LAST:event_EditMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }
    
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(65,59,94));
    }
    
    
    private void resetColor(JPanel pane)
    {
        pane.setBackground(new Color(19,10,52));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttendenceLebel;
    private javax.swing.JPanel AttendencePanel;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel ClassText;
    private javax.swing.JLabel Edit;
    private javax.swing.JLabel Home1;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel Homework;
    private javax.swing.JPanel HomeworkPanel;
    private javax.swing.JPanel HomeworkPanel1;
    private javax.swing.JPanel HomeworkPanel2;
    private javax.swing.JLabel IDFDB;
    private javax.swing.JLabel IDTest1;
    private javax.swing.JPanel LeftCeditPanel;
    private javax.swing.JLabel MenuText;
    private javax.swing.JPanel MessegePanel;
    private javax.swing.JLabel NameFDB;
    private javax.swing.JLabel NameText2;
    private javax.swing.JLabel ResultLebel;
    private javax.swing.JLabel Section;
    private javax.swing.JLabel SectionText;
    private javax.swing.JLabel SideMenuShow;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel attendance_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JPanel home_btn;
    private javax.swing.JLabel homeworkLabel;
    private javax.swing.JPanel homework_btn;
    private javax.swing.JPanel ind_0;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel messegeLebel;
    private javax.swing.JPanel messege_btn;
    private javax.swing.JPanel myNoticePanel;
    private javax.swing.JButton nextHomeworkButton;
    private javax.swing.JTable noticeBoardTable;
    private javax.swing.JLabel noticeLebel;
    private javax.swing.JPanel noticePanel;
    private javax.swing.JPanel notices_btn;
    private javax.swing.JLabel postDateLabel;
    private javax.swing.JButton previousHomeworkButton;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel result_btn;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel sideMenuHide;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel totalMarksLabel;
    // End of variables declaration//GEN-END:variables
}
